# Map of enabled communication mediums. The `communications` property name is an alias for a given configuration.
#
# Format: communications.<alias>
communications:
  'default-group':
    # Settings for Slack
    slack:
      enabled: true
      channels:
        'alias':
          name: 'botkube-demo'
          bindings:
            executors:
              - 'kubectl-read-only'
            sources:
              - 'k8s-events'
      token: 'xoxb-3933899240838-4098910723926-IauDChNfNFKO6ULYVI7Etj1i'
      #appToken: 'xapp-1-A03V0NT62H2-4071048488855-11a381a4bea79588c6ffd2c95b40348ede31741f21e2e4ca62b23ca9cda87412'
      #botToken: 'xoxb-3560138036753-3969758134391-qTU3CrDPXrCP4aW5jrbQcRF9'
      notification:
        type: short                             # Change notification type short/long you want to receive. Type is optional and default is short.

    # Settings for Mattermost
    mattermost:
      enabled: false
      url: 'https://kubeshop.cloud.mattermost.com/'              # URL where Mattermost is running. e.g https://example.com:9243
      token: 'fiqfwnwd1pgk7k9s6x7y5wx5ww'                 # Personal Access token generated by BotKube user
      team: 'kubeshop'                   # Mattermost Team to configure with BotKube
      botName: 'BotKube'                        # Bot name
      channels:
        'alias':
          name: 'botkube'            # Mattermost Channel for receiving BotKube alerts:
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-events
      notification:
        type: short                             # Change notification type short/long you want to receive. Type is optional and default is short.

    # Settings for MS Teams
    teams:
      enabled: false
      appID: 'APPLICATION_ID'
      appPassword: 'APPLICATION_PASSWORD'
      botName: 'BotKube'
      notification:
        type: short
      port: 3978

    # Settings for Discord
    discord:
      enabled: false
      token: 'DISCORD_TOKEN'                    # BotKube Bot Token
      botID: 'DISCORD_BOT_ID'                   # BotKube Application Client ID
      channels:
        'alias':
          id: 'DISCORD_CHANNEL_ID'            # Discord Channel id for receiving BotKube alerts:
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-events
      notification:
        type: short                             # Change notification type short/long you want to receive. Type is optional and default is short.


    # Settings for ELS
    elasticsearch:
      enabled: false
      awsSigning:
        enabled: false                          # enable awsSigning using IAM for Elastisearch hosted on AWS, if true make sure AWS environment variables are set. Refer https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
        awsRegion: 'us-east-1'                  # AWS region where Elasticsearch is deployed
        roleArn: ''                             # AWS IAM Role arn to assume for credentials, use this only if you dont want to use the EC2 instance role or not running on AWS instance
      server: 'ELASTICSEARCH_ADDRESS'           # e.g https://example.com:9243
      username: 'ELASTICSEARCH_USERNAME'        # Basic Auth
      password: 'ELASTICSEARCH_PASSWORD'
      skipTLSVerify: false                      # toggle verification of TLS certificate of the Elastic nodes. Verification is skipped when option is true. Enable to connect to clusters with self-signed certs
      # ELS index settings
      indices:
        'alias':
          name: botkube
          type: botkube-event
          shards: 1
          bindings:
            sources:
              - "k8s-events"
            # executors - not allowed in this case, ES is "sink" only.
    # Settings for Webhook
    webhook:
      enabled: false
      url: 'WEBHOOK_URL'                        # e.g https://example.com:80
      bindings:
        # -- Notification sources configuration for the webhook.
        sources:
          - k8s-events
