apiVersion: v1
name: botkube
home: https://botkube.io
version: 1.60.0-rc.5
appVersion: 1.60.0-rc.5
icon: https://botkube.io/images/botkube.ico
description: Controller for the BotKube Slack app which helps you monitor your Kubernetes cluster,
 debug deployments and run specific checks on resources in the cluster.
sources:
  - https://github.com/kubeshop/botkube
keywords:
  - botkube
  - kubernetes
  - kubernetes-monitoring
  - kubernetes-controller
  - kubernetes-bot
  - chatops
  - bot
  - botops
maintainers:
  - name: BotKube Dev Team
    email: dev-team@botkube.io
