name: Code freeze

on:
  workflow_dispatch:
    inputs:
      from:
        type: string
        description: Branch, commit, or commit SHA
        required: true
        default: main
      version:
        type: string
        description: Version of the next release
        required: true

env:
  git-user: github-actions[bot]
  git-email: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  code-freeze:
    name: Create release/${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.from }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set git 'user.name' and 'user.email'
        run: |
          git config user.name "${{ env.git-user }}"
          git config user.email ${{ env.git-email }}

      - name: Create a release branch
        run: |
          git checkout -b release/${{ inputs.version }}

      - name : Push new branch
        run: git push origin release/${{ inputs.version }}