name: Release
on:
  push:
    tags:
      - '*'

env:
  git-user: github-actions[bot]
  git-email: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set git 'user.name' and 'user.email'
        run: |
          git config user.name "${{ env.git-user }}"
          git config user.email ${{ env.git-email }}

#      - name: Setup Go
#        uses: actions/setup-go@v3
#        with:
#          go-version-file: 'go.mod'
#          cache: true
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Docker Login
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GH_TOKEN }}

      - name: Prepare GoReleaser Env
        run: |
          echo "IMAGE_REPOSITORY=$GITHUB_REPOSITORY_OWNER/botkube" >> $GITHUB_ENV 
          echo "TEST_IMAGE_REPOSITORY=$GITHUB_REPOSITORY_OWNER/botkube-test" >> $GITHUB_ENV 

#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v3
#        with:
#          args: release --rm-dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          IMAGE_TAG: ${{ github.ref_name }}
#          ANALYTICS_API_KEY: ${{ secrets.ANALYTICS_API_KEY }}

      - name: Update Chart YAML Files
        run: |
          HELM_FOLDER=$(echo "${{ github.workspace }}/helm")
          CHART_CURRENT_VERSION=$(sed -nE 's/^version\s*:\s*([^\s\/]*).*/\1/p' ${HELM_FOLDER}/botkube/Chart.yaml)
          find ${HELM_FOLDER} -name "*.yaml" -exec sed -i "s/${CHART_CURRENT_VERSION}/${{ github.ref_name }}/g" {} +
          if [[ $(git diff --stat) != '' ]]; then
            git commit -am "Helm version: ${CHART_CURRENT_VERSION} is replaced with ${{ github.ref_name }}"
            git push origin release/${{ github.ref_name }}
          fi